### ISSUE TITLE
Remove "rpc" field

### ISSUE THREAD

**Issue by pedrouid** [UCRegistry/registry#6]
By including RPC urls we are incentivizing developers to use remote nodes which will lead to more centralization. We want instead to provide the data for them to run their nodes

**Comment by RiccardoM** [comment]
What if a mobile developer wants to use this registry in order to connect to existing nodes while developing a mobile wallet? 

I think that removing the whole field could lead to the registry not being used by everyone. Requiring a developer to run his node it's not the best approach IMO. 

I think we should leave this field along with the field described in #7. Not everyone could be able or even want to run his node.

**Comment by antoineherzog** [comment]
I understand the utility for testing purposes of having this field for developper. Maybe we shoudl rename it: test_rpc ? or example_test_rpc?
